# Stage 1: Build stage
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS builder

# Set the working directory
WORKDIR /promtail

# Set build argument for Promtail version
ARG PROMTAIL_VERSION=2.4.1

# Download and extract Promtail
ADD https://github.com/grafana/loki/releases/download/v${PROMTAIL_VERSION}/promtail-windows-amd64.exe.zip .

RUN powershell -Command Expand-Archive promtail-windows-amd64.exe.zip -DestinationPath .

# Stage 2: Final stage
FROM mcr.microsoft.com/windows/servercore:ltsc2019 

# Set labels
LABEL \
    Owner="Muhammed Iqbal" \
    Base="Windows Nano Server LTSC 2022" \
    Application="Promtail" \
    Version=${PROMTAIL_VERSION}

# Set the working directory
WORKDIR /promtail

# Copy the Promtail binary from the builder stage
COPY --from=builder /promtail/promtail-windows-amd64.exe .

# Expose the necessary ports
EXPOSE 3101

# Set Civetweb directory
ARG CIVETWEB_DIR=/civetweb

# Download and extract Civetweb
ADD https://github.com/civetweb/civetweb/releases/download/v1.16/CivetWeb_Win64_V1.16.zip .

RUN powershell -Command Expand-Archive civetweb-win64.zip -DestinationPath ${CIVETWEB_DIR}

# Set the command to run Promtail with Civetweb for metrics and logging to standard out
ENTRYPOINT ["promtail-windows-amd64.exe", "-server", "-log.format", "json", "-log.encoding", "console"]
