# Use a Windows base image
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS downloader

# Set working directory
WORKDIR C:\temp

# Download Promtail binary
ARG PROMTAIL_VERSION="2.4.1"
RUN powershell -Command `
    $PROMTAIL_URL = "https://github.com/grafana/loki/releases/download/v${Env:PROMTAIL_VERSION}/promtail-windows-amd64.zip"; `
    Invoke-WebRequest -Uri $PROMTAIL_URL -OutFile "promtail-windows-amd64.zip"

# Extract Promtail binary
RUN powershell -Command Expand-Archive -Path 'C:\temp\promtail-windows-amd64.zip' -DestinationPath 'C:\temp\promtail'

# Final image
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Set working directory
WORKDIR C:\Promtail

# Copy Promtail binary from downloader stage
COPY --from=downloader C:\temp\promtail\promtail-windows-amd64.exe .

# Set entrypoint
ENTRYPOINT ["promtail-windows-amd64.exe"]
